#################################################################
# MultiQC Defaults
#################################################################
# This file contains the default configuration options
# for MultiQC. IT SHOULD NOT BE EDITED. If you want to
# change any of these config options, create a new file
# in any of the following locations:
#  1. <installation_dir>/multiqc_config.yaml (not pip or conda)
#  2. ~/.multiqc_config.yaml
#  3. <working directory>/multiqc_config.yaml
#################################################################

#title: Mapache report
subtitle: null
intro_text: This is an extended report of the mapping pipeline mapache (https://github.com/sneuensc/mapache). Mapache is a light weighted mapping pipeline for ancient DNA using the workflow manager snakemake. The report allows getting insights into the different processes. 
report_comment: null
report_header_info: null
show_analysis_paths: True
show_analysis_time: True
config_file: null
custom_logo: 'workflow/report/mapache_logo.png'
custom_logo_url: null
custom_logo_title: null
simple_output: false
template: 'default'
profile_runtime: False
pandoc_template: null
read_count_multiplier: 0.001
read_count_prefix: 'K'
read_count_desc: 'thousands'
long_read_count_multiplier: 0.001
long_read_count_prefix: 'K'
long_read_count_desc: 'thousands'
base_count_multiplier: 0.000001
base_count_prefix: 'Mb'
base_count_desc: 'millions'
output_fn_name: 'multiqc_mapache.html'
data_dir_name: 'multiqc_mapache_data'
plots_dir_name: 'multiqc_mapache_plots'
data_format: 'tsv'
module_tag: []
force: false
prepend_dirs: false
prepend_dirs_depth: 0
prepend_dirs_sep: ' | '
file_list: false

make_data_dir: true
zip_data_dir: true
data_dump_file: true
megaqc_url: false
megaqc_access_token: null
megaqc_timeout: 30
export_plots: false
plots_force_flat: false
plots_force_interactive: false
plots_flat_numseries: 100
num_datasets_plot_limit: 50
collapse_tables: true
max_table_rows: 500
table_columns_visible: {}
table_columns_placement: {}
table_cond_formatting_colours:
    - blue: '#337ab7'
    - lbue: '#5bc0de'
    - pass: '#5cb85c'
    - warn: '#f0ad4e'
    - fail: '#d9534f'
table_cond_formatting_rules:
    all_columns:
        pass:
            - s_eq: 'pass'
            - s_eq: 'true'
        warn:
            - s_eq: 'warn'
            - s_eq: 'unknown'
        fail:
            - s_eq: 'fail'
            - s_eq: 'false'
    # PURPLE module - QC Status column
    # TODO: Should update the table plotting code so that this can go in pconfig
    QCStatus:
        fail:
            - s_contains: 'fail'
decimalPoint_format: null
thousandsSep_format: null
#remove_sections: 
#    - fastqc_status_checks

section_comments: {}
#lint: False
custom_plot_config: {}

ignore_symlinks: false
ignore_images: true
fn_ignore_dirs:
    - 'multiqc_data'
    - 'icarus_viewers'       # quast
    - 'runs_per_reference'   # quast
    - 'not_aligned'          # quast
    - 'contigs_reports'      # quast

fn_ignore_paths:
    - '*/work/??/??????????????????????????????' # Nextflow work directories - always same hash lengths
    




data_format_extensions:
    tsv: 'txt'
    json: 'json'
    yaml: 'yaml'
export_plot_formats:
    - 'png'
    - 'svg'
    - 'pdf'

# Custom Config settings
custom_content:
    order: []

# Option to disable sample name cleaning if desired
fn_clean_sample_names: true

# Used for cleaning sample names. Should be strings.
# NB: These are removed in order!
fn_clean_exts:
    - '.gz'
    - '.fastq'
    - '.fq'
    - '.bam'
    - '.sam'
    - '.sra'
    - '.vcf'
    - '.dat'
    - '_tophat'
    - '.log'
    - '.stderr'
    - '.out'
    - '.spp'
    - '.fa'
    - '.fasta'
    - '.png'
    - '.jpg'
    - '.jpeg'
    - '.html'
    - 'Log.final'
    - 'ReadsPerGene'
    - '.flagstat'
    - '_star_aligned'
    - '_fastqc'
    - '.hicup'
    - '.counts'
    - '_counts'
    - '.txt'
    - '.tsv'
    - '.csv'
    - '.aligned'
    - 'Aligned'
    - '.merge'
    - '.deduplicated'
    - '.dedup'
    - '.clean'
    - '.sorted'
    - '.report'
    - '| stdin'
    - '.geneBodyCoverage'
    - '.inner_distance_freq'
    - '.junctionSaturation_plot.r'
    - '.pos.DupRate.xls'
    - '.GC.xls'
    - '_slamdunk'
    - '_bismark'
    - '.conpair'
    - '.concordance'
    - '.contamination'
    - '.BEST.results'
    - '_peaks.xls'
    - '.relatedness'
    - '.cnt'
    - '.aqhist'
    - '.bhist'
    - '.bincov'
    - '.bqhist'
    - '.covhist'
    - '.covstats'
    - '.ehist'
    - '.gchist'
    - '.idhist'
    - '.ihist'
    - '.indelhist'
    - '.lhist'
    - '.mhist'
    - '.qahist'
    - '.qhist'
    - '.rpkm'
    - '.selfSM'
    - '.extendedFrags'
    - '_SummaryStatistics'
    - '.purple.purity'
    - '.purple.qc'
    - '.settings'
    - '_stats'

# These are removed after the above, only if sample names
# start or end with this string. Again, removed in order.
fn_clean_trim:
    - '.'
    - ':'
    - '_'
    - '-'
    - '.r'
    - '_val'
    - '.idxstats'
    - '_trimmed'
    - '.trimmed'
    - '.csv'
    - '.yaml'
    - '.yml'
    - '.json'
    - '_mqc'
    - 'short_summary_'
    - '_summary'
    - '.summary'
    - '.align'
    - '.h5'
    - '_matrix'
    - '.stats'
    - '.hist'

# Files to ignore when indexing files.
# Grep file match patterns.
fn_ignore_files:
    - '.DS_Store'
    - '*.bam'
    - '*.bai'
    - '*.sam'
    - '*.fq.gz'
    - '*.fastq.gz'
    - '*.fq'
    - '*.fastq'
    - '*.fa'
    - '*.gtf'
    - '*.bed'
    - '*.vcf'
    - '*.txt.gz'
    - '*.pdf'
    - '*[!_][!m][!q][!c].html'
    - '*.md5'

# Favourite modules that should appear at the top in preference
# This is in addition to those below. These appear above _all_ other
# modules (even those not present in the below list).
top_modules: []

# Order that modules should appear in report. Try to list in order of analysis.
module_order:
    # MultiQC general module for catching output from custom scripts
    - 'custom_content'

    - sentieon:
        module_tag:
            - DNA
    - sexdeterrmine:
        module_tag:
            - DNA

    - 
    # Pre-alignment QC
    - fastqc:
        name: "FastQC (raw)"
        anchor: "fastqc_raw"
        info: "This section of the report shows FastQC results on the original raw reads."
        custom_config: 
        path_filters:
          - "*/01_files_orig/*_fastqc.zip"
        module_tag:
            - RNA
            - DNA
    - adapterRemoval:
        module_tag:
            - RNA
            - DNA
            - ancient
    - trimmomatic:
        module_tag:
            - RNA
            - DNA
    - fastqc:
        name: "FastQC (trimmed)"
        anchor: "fastqc_trimmed"
        info: "This section of the report shows FastQC results after adapter trimming."
        target: ""
        path_filters:
            - "*/01_adapter_removal*/*_fastqc.zip"
        module_tag:
            - RNA
            - DNA
    
    # Alignment tool stats
    - bowtie2:
        module_tag: 
    
    # Post-alignment QC fastq level
    - samtools:
        name: "Samtools  (fastq)"
        anchor: "samtools_fastq"
        info: "This section of the report shows the summary of the final bam file of the fastq level."
        target: ""
        path_filters:
            - "*/04_final_fastq/*_stats.txt"
        module_tag:
            - DNA
            - RNA

    # Post-alignment QC library level
    - samtools:
        name: "Samtools  (library)"
        anchor: "samtools_library"
        info: "This section of the report shows the summary of the final bam file of the library level."
        target: ""
        path_filters:
            - "*/03_final_library/*_stats.txt"
        module_tag:
            - DNA
            - RNA
    - dedup:
        module_tag:
            - DNA
            - ancient
    - damageprofiler:
        module_tag:
            - DNA
            - ancient
    - picard:
        name: "PICARD MarkDuplicates"
        path_filters:
            - "*/02_library/01_duplicated/01_markduplicates/*.stats"
        module_tag:
            - DNA
            - RNA
    
    # Post-alignment QC sample level
    - samtools:
        name: "Samtools  (sample)"
        anchor: "samtools_sample"
        info: "This section of the report shows the summary of the final bam file of the sample level."
        target: ""
        path_filters:
            - "*/03_final_sample/*_stats.txt"
        module_tag:
            - DNA
            - RNA

    - qualimap:
        module_tag:
            - DNA
            - RNA

