## get the corresponding bam file (generic, across all levels):
##  - if final bam file: get the corresponding final bam file at the different levels
##  - otherwise retake the path
def get_bam_file(wc):
    paths = list(pathlib.Path(wc.file).parts)
    if paths[1] == "04_final_fastq":  ## fastq
        file = get_final_bam_FASTQ(
            Wildcards(
                fromdict={
                    "folder": wc.folder,
                    "sm": paths[3],
                    "lb": paths[4],
                    "id": paths[5],
                    "genome": wc.genome,
                }
            )
        )
    elif paths[1] == "02_bam_after_rmDup":  ## library_after_rmDup
        file = get_bam_after_rmDup(
            Wildcards(
                fromdict={
                    "folder": wc.folder,
                    "sm": paths[3],
                    "lb": paths[4],
                    "genome": wc.genome,
                }
            )
        )
    elif paths[1] == "03_final_library":  ## library final
        file = get_final_bam_LB(
            Wildcards(
                fromdict={
                    "folder": wc.folder,
                    "sm": paths[3],
                    "lb": paths[4],
                    "genome": wc.genome,
                }
            )
        )
    elif paths[1] == "03_final_sample":  ## sample final
        file = (
            f"{wc.folder}/03_sample/03_final_sample/01_bam/{paths[3]}.{wc.genome}.bam"
        )

    else:  ## the path is the right one (symlink)
        file = f"{wc.folder}/{wc.file}.{wc.genome}.bam"

    # print(f"get_bam_file: {file}")
    return file

## bamdamage ####################################################################################################
## get all files generated by the deamination inference
def get_damage_output(ll):
    selected = get_param(["stats", "damage", "level"], ['SM', 'LB', 'LB_rmDup'], combination=True)
    level = list(set(ll).intersection(selected))
    if run_damage == "bamdamage":
        files = []
        if "LB_rmDup" in level:
            files += [
                f"{RESULT_DIR}/04_stats/01_sparse_stats/02_library/02_bam_after_rmDup/bamdamage/{sm}/{lb}.{genome}.{type}.{ext}"
                for sm, smVals in SAMPLES.items()
                for lb in smVals
                for type in ["dam", "length"]
                for ext in ["pdf", "svg"]
                for genome in GENOMES
            ]

        if "LB" in level:
            files += [
                f"{RESULT_DIR}/04_stats/01_sparse_stats/02_library/03_final_library/bamdamage/{sm}/{lb}.{genome}.{type}.{ext}"
                for sm, smVals in SAMPLES.items()
                for lb in smVals
                for type in ["dam", "length"]
                for ext in ["pdf", "svg"]
                for genome in GENOMES
            ]

        if "SM" in level:
            files += [
                f"{RESULT_DIR}/04_stats/01_sparse_stats/03_sample/03_final_sample/bamdamage/{sm}.{genome}.{type}.{ext}"
                for sm in SAMPLES_FINAL
                for type in ["dam", "length"]
                for ext in ["pdf", "svg"]
                for genome in GENOMES
            ]

    elif run_damage == "mapDamage":
        folder = "01_mapDamage"
        files = [
            f"{{RESULT_DIR}}/04_stats/01_sparse_stats/02_library/{folder}/{sm}/{lb}.{genome}_results_mapDamage/Fragmisincorporation_plot.pdf"
            for sm, smVals in SAMPLES.items()
            for lb in smVals
            for genome in GENOMES
        ]
    else:  ## if False
        files = []
    # print(files)
    return files

## mapping_stats ####################################################################################################

def get_stat_csv_files(ll):
    selected = get_param(["stats", "mapping_stats"], ['SM', 'LB', 'LB_rmDup', 'FASTQ'], combination=True)
    level = list(set(ll).intersection(selected))
    files = [
        f"{RESULT_DIR}/04_stats/03_summary/{level}/{level}_stats.csv" 
        for level in level
    ]
    return files


def get_stat_plot_files(ll=["SM", "LB", "LB_rmDup"]):
    selected = get_param(["stats", "mapping_stats"], ['SM', 'LB', 'LB_rmDup'], combination=True)
    level = list(set(ll).intersection(selected))
    files = [
        f"{RESULT_DIR}/04_stats/03_summary/{level}/{plot}.svg"
        for level in level
        for plot in [
            "1_nb_reads",
            "2_mapped",
            "3_endogenous",
            "4_duplication",
            "5_AvgReadDepth",
            "6_Sex",
        ]
    ]
    return files



## samtools_stats ####################################################################################################
def get_samtools_stats_files():
    samtools_stats = (
        [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/{file}_stats.txt"
            for genome in GENOMES
            for sm, smVals in SAMPLES.items()
            for lb, lbVals in smVals.items()
            for id in lbVals
            for file in [
                f"01_fastq/04_final_fastq/01_bam/{sm}/{lb}/{id}.{genome}",
                f"02_library/03_final_library/01_bam/{sm}/{lb}.{genome}",
            ]
        ]
        + [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/03_sample/03_final_sample/01_bam/{sm}.{genome}_stats.txt"
            for genome in GENOMES
            for sm in SAMPLES_FINAL
        ]
        + [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/{file}_stats.txt"
            for genome, gVal in EXTERNAL_SAMPLES.items()
            for sm in gVal
            for file in [f"03_sample/03_final_sample/01_bam/{sm}.{genome}"]
        ]
    )
    # print(samtools_stats)
    return list(set(samtools_stats))  ## remove duplicates


## depth ####################################################################################################
def get_length_files(level=["SM"]):
    files = []

    if "FASTQ" in levels:
        files += [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/01_fastq/04_final_fastq/01_bam/{sm}/{lb}/{id}.{genome}_length.txt"
            for genome in GENOMES
            for sm, smVals in SAMPLES.items()
            for lb, lbVals in smVals.items()
            for id in lbVals
        ]

    if "LB_rmDup" in levels:
        files += [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/02_library/03_library_rmDup/01_bam/{sm}/{lb}.{genome}_length.txt"
            for genome in GENOMES
            for sm, smVals in SAMPLES.items()
            for lb in smVals
        ]

    if "LB" in levels:
        files += [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/02_library/03_final_library/01_bam/{sm}/{lb}.{genome}_length.txt"
            for genome in GENOMES
            for sm, smVals in SAMPLES.items()
            for lb in smVals
        ]

    if "SM" in levels:
        files += [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/03_sample/03_final_sample/01_bam/{sm}.{genome}_length.txt"
            for genome in GENOMES
            for sm in SAMPLES_FINAL
        ]

        if len(EXTERNAL_SAMPLES):
            files += [
                f"{RESULT_DIR}/04_stats/01_sparse_stats/03_sample/03_final_sample/01_bam/{sm}.{genome}_length.txt"
                for genome, gVal in EXTERNAL_SAMPLES.items()
                for sm in gVal
            ]

    return list(set(files))  ## remove duplicates


## preseq ####################################################################################################
def get_preseq_files_genome(ext, genome):
    files = [
        f"{RESULT_DIR}/04_stats/01_sparse_stats/02_library/02_bam_before_rmDup/01_preseq/{sm}/{lb}.{genome}_preseq.{ext}"
        for sm in SAMPLES
        for lb in SAMPLES[sm]
    ]
    return files


def get_preseq_files(ext):
    files = [
        get_preseq_files_genome(ext, genome)
        for genome in GENOMES
    ]
    #print(files)
    return files


## bam index ####################################################################################################
def get_idxstats_files():
    idxstats = (
        [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/{file}_idxstats.txt"
            for genome in GENOMES
            for sm, smVals in SAMPLES.items()
            for lb in smVals
            for file in [
                f"02_library/03_final_library/01_bam/{sm}/{lb}.{genome}",
            ]
        ]
        + [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/03_sample/03_final_sample/01_bam/{sm}.{genome}_idxstats.txt"
            for genome in GENOMES
            for sm in SAMPLES_FINAL
        ]
        + [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/{file}_idxstats.txt"
            for genome, gVal in EXTERNAL_SAMPLES.items()
            if len(EXTERNAL_SAMPLES)
            for sm in gVal
            for file in [f"03_sample/03_final_sample/01_bam/{sm}.{genome}"]
        ]
    )
    return list(set(idxstats))  ## remove duplicates


## qualimap ####################################################################################################
def get_qualimap_files(ll):
    if not str2bool(get_param(["stats", "qualimap", "run"], ["False", "True"])):
        return []

    selected = get_param(["stats", "qualimap", "level"], ['SM', 'LB', 'LB_rmDup', 'FASTQ'], combination=True)
    level = list(set(ll).intersection(selected))
    files = []
    if "LB_rmDup" in level:
        files += [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/02_library/02_bam_after_rmDup/01_bam/{sm}/{lb}.{genome}_qualimap"
            for genome in GENOMES
            for sm, smVals in SAMPLES.items()
            for lb in smVals
        ]

    if "LB" in level:
        files += [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/02_library/03_final_library/01_bam/{sm}/{lb}.{genome}_qualimap"
            for genome in GENOMES
            for sm, smVals in SAMPLES.items()
            for lb in smVals
        ]

    if "SM" in level:
        files += [
            f"{RESULT_DIR}/04_stats/01_sparse_stats/03_sample/03_final_sample/01_bam/{sm}.{genome}_qualimap"
            for genome in GENOMES
            for sm in SAMPLES_FINAL
        ]

        if len(EXTERNAL_SAMPLES):
            files += [
                f"{RESULT_DIR}/04_stats/01_sparse_stats/03_sample/03_final_sample/01_bam/{sm}.{genome}_qualimap"
                for genome, gVal in EXTERNAL_SAMPLES.items()
                for sm in gVal
            ]
    # print( files)
    return files



def compute_qualimap(level, wc):
    return str2bool(
        get_paramGrp(["stats", "qualimap", "run"], ["False", "True"], wc)
        and (
            level
            in str2list(
                get_paramGrp(
                    ["stats", "qualimap", "level"],
                    ["SM", "LB", "LB_rmDup"],
                    wc,
                    combination=True,
                )
            )
        )
    )