software:
    picard_jar: 'picard'
    gatk3_jar: 'GenomeAnalysisTK'

envmodules:
    samtools:       "gcc samtools/1.12"
    bowtie2:        "gcc bowtie2/2.4.2"
    bwa:            "gcc bwa/0.7.17"
    picard:         "gcc picard/2.24.0"
    gatk3:          "gcc gatk/3.8-1"
    fastqc:         "gcc fastqc/0.11.9"
    r:              "gcc r/4.0.4"
    adapterremoval: "gcc adapterremoval/2.3.2"
    mapdamage:      ""
    multiqc:        ""
    bedtools:       "gcc bedtools2/2.29.2"
    seqtk:          ""

##########################################################################################
##########################################################################################

#workdir: 
sample_file: config/PasoDelIndio.txt

genome: 
    hg19: 
        fasta: /work/FAC/FBM/DBC/amalaspi/popgen/shared_ressources/reference_human/hs.build37.1/hs.build37.1.fa
        # mtChr: MT
        # If you want the DoC to be reported for some chromosomes in the main stats table, list them below. 
        depth_chromosomes: "X,Y,MT,4"

        # parameters specific to sex inference
        sex_inference:
            run: True
            # uncomment options below if you need to change any value
            params:
                # you can paste any python expression here, in single quotes ('):
                    # '[f"chr{x}" for x in range(1,23)]' # chr1,chr2,chr3,etc.
                    # [x for x in range(1,23)] # 1,2,3,etc.
                autosomes: '[x for x in range(1,23)]'
                sex_chr: 3
                system: XY
                signif: 0.9
                thresholds:  list( "XX" = c(0.8, 1), "XY" = c(0, 0.6), "consistent with XX but not XY" = c(0.6, 1), "consistent with XY but not XX" = c(0, 0.8) )
    GRCh38: 
        fasta: /work/FAC/FBM/DBC/amalaspi/popgen/shared_ressources/reference_human/GCA_000001405.15_GRCh38.p13_onlyChrom/GCA_000001405.15_GRCh38.fa
        # If you want the DoC to be reported for some chromosomes in the main stats table, list them below.
        depth_chromosomes: "chrX,chrY,chrM"
        # any python evaluation is allowed. Please use double quotes (") instead of single quotes (')
        #mtChr: chrM
        #     # either of XY, ZW, XO or ZO
        sex_inference:
            run: True
            # uncomment options below if you need to change any value
            params:
                # you can paste any python expression here, in single quotes ('):
                    # '[f"chr{x}" for x in range(1,23)]' # chr1,chr2,chr3,etc.
                    # [x for x in range(1,23)] # 1,2,3,etc.
                autosomes: '[f"chr{x}" for x in range(1,23)]'
                sex_chr: chrY
                # system: XY
                # signif: 0.95
                # thresholds:  list( "XX" = c(0.8, 1), "XY" = c(0, 0.6), "consistent with XX but not XY" = c(0.6, 1), "consistent with XY but not XX" = c(0, 0.8) )
    

delim: '\s+'
#delim: ' '
#delim: "\t"

## global variables to define about resource increments after job failure
## 0: no change between failures
## 1: doubling after each failure
memory_increment_ratio: 1
runtime_increment_ratio: 0

## indexing
indexing:
    mem: 16
    threads: 1
    time: 2
    bwa_params: ''
    bowtie2_params: ''
    samtools_params: ''
    picard_params: ''

##########################################################################################
## FASTQ level

## subsampling (optional)
subsampling:
    run: False
    params: '-s1'
    number: 1000

# adapter_removal (optional)
adapterremoval:
    run: True
    params: '--minlength 30 --trimns --trimqualities'
    threads: 4 
    mem: 4 ## in GB
    time: 2

## mapping (bwa_aln, bwa_mem, bowtie2)
mapping:
    bwa_aln_params: '-l 1024'   
    bwa_samse_params: '-n 3'
    bwa_sampe_params: ''
    bwa_mem_params: ''
    bowtie2_params: ''
    threads: 4
    mem: 16
    time: 30
mapper: 'bwa_aln'


## samtools_sort
sorting:
    threads: 4
    mem: 16
    time: 10


## samtools_filter
filtering:
    run: True
    threads: 4
    mem: 16
    time: 2
    save_low_qual: False

##########################################################################################
## library level

## merge_bam_fastq2library
## merge_bam_library2sample
merging:
    threads: 4
    mem: 16
    time: 2

## extract_duplicates (optional)
## in this case parameter 'rmdup_params' has NOT to be set to 'REMOVE_DUPLICATES=true'
markduplicates:
    run: True  
    params: 'REMOVE_DUPLICATES=true'
    threads: 4
    mem: 16
    time: 2
    save_duplicates: remove  ## remove, mark, extract


## mapDamage (optional, by default not run: see below)
mapdamage:
    run_rescale: False
    params: ''
    time: 2
    threads: 1 ## hardcoded at 1
    mem: 8

bamdamage:
    run: False
    params: ''
    fraction: 0
    time: 2
    threads: 1 ## hardcoded at 1
    mem: 8


##########################################################################################
## sample level

## realign and samtools_index (optional)
realign:
    run: True
    threads: 4
    mem: 16
    time: 4

## samtools_calmd (optional)
compute_md:
    run: True
    threads: 4
    mem: 16
    time: 2


##########################################################################################
## stats on the final bam file
stats:

## mds
    run_bammds: False

## deamination (has to be added to the library and final bam file)
    run_damage: 'bamdamage'        #("False", "mapDamage", "bamdamage")
    bamdamage_fraction: 5000
    bamdamage_params: ' --rlength 300 '
# specific to Mapping statistics plot in the report
    plots:
        # x_axis: either "sample" or "genome"
        # if n_samples > n_genomes, we recommend to set this option to "sample"
        # if n_genomes > n_samples, we recommend to set this option to "genome"
        # default: sample
        x_axis: genome
        split_plot: T # possible values: FALSE, F, TRUE, T
        # set maximum number of bars (columns) on the x-axis across n_row rowa. 
        # We recommend
        # a large n_col (around 20) and/or a small n_row (1 to 3)
        n_col: 11
        n_row: 3
