channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake = 6.4.1
  - adapterremoval = 2.3.2
  - bwa = 0.7.17
  - bowtie2 = 2.4.4
  - fastqc = 0.11.9
  - gatk = 3.8
  - mapdamage2 = 2.2.1
  - picard = 2.25.5
  - samtools = 1.14
  - bedtools = 2.30.0
  - seqtk = 1.3
  - dedup = 0.12.8
  - R = 4.0
  - r-ggplot2
  - r-rcolorbrewer
  - r-reshape2
  - r-svglite
  - r-gridextra
