channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - conda
  - mamba
  - snakemake=8.25.4
  - snakemake-executor-plugin-slurm
  - snakemake-storage-plugin-ftp 
  - snakefmt
  - adapterremoval=2.3.4
  - bamutil=1.0.15
  - bcftools=1.21
  - bedtools=2.31.1
  - bowtie2=2.5.4
  - bwa=0.7.18
  - dedup=0.12.9
  - fastp=0.24.0
  - fastqc=0.12.1
  - gatk=3.8
  - glimpse-bio=1.1.1
  - glimpse-bio=2.0.1
  - mapdamage2=2.2.2
  - multiqc=1.25.2
  - picard=3.3.0
  - qualimap=2.3
  - samtools=1.21
  - seqtk=1.4
  - R=4.4
  - r-ggplot2
  - r-gridextra
  - r-rcolorbrewer
  - r-svglite
  - r-tidyverse
