channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake=7.14.0
  - mamba
  - adapterremoval=2.3.2
  - bwa=0.7.17
  - bowtie2=2.4.4
  - fastqc=0.11.9
  - gatk=3.8
  - mapdamage2=2.2.1
  - picard=2.25.5
  - samtools=1.14
  - bedtools=2.30.0
  - seqtk=1.3
  - dedup=0.12.8
  - qualimap=2.2.2d
  - multiqc=1.11
  - charset-normalizer=2.0.0
  - glimpse-bio=1.1.1
  - bcftools=1.15
  - R=4.0
  - r-ggplot2
  - r-rcolorbrewer
  - r-reshape2
  - r-svglite
  - r-gridextra
  - r-data.table
